id: intelligent-monitor
namespace: sentinel

tasks:
  # Debug log to confirm the flow runs every 30 seconds
  - id: debug-start
    type: io.kestra.plugin.core.log.Log
    message: "==== SENTINEL execution tick - {{ execution.id }} - {{ now() }} ===="

  # 1. Fetch Health Data (Parallel)
  - id: fetch-metrics
    type: io.kestra.plugin.core.flow.Parallel
    allowFailure: true
    tasks:
      - id: get-auth
        type: io.kestra.plugin.core.http.Request
        uri: http://auth-service:3001/health
        allowFailure: true

      - id: get-payment
        type: io.kestra.plugin.core.http.Request
        uri: http://payment-service:3002/health
        allowFailure: true

      - id: get-notify
        type: io.kestra.plugin.core.http.Request
        uri: http://notification-service:3003/health
        allowFailure: true


  # 2. Decide whether AI analysis is needed
  - id: ai-needed
    type: io.kestra.plugin.core.flow.If
    condition: >
      {{ 
        (outputs['get-auth'].code | default(500)) != 200 or
        (outputs['get-payment'].code | default(500)) != 200 or
        (outputs['get-notify'].code | default(500)) != 200
      }}
    then:
      # 2a. AI Analysis ONLY when something is down
      - id: ai-analysis
        type: io.kestra.plugin.core.http.Request
        uri: https://api.groq.com/openai/v1/chat/completions
        method: POST
        headers:
          Authorization: "Bearer {{ secret('GROQ_API_KEY') }}"
          Content-Type: "application/json"
        body: |
          {
            "model": "llama-3.3-70b-versatile",
            "messages": [
              {
                "role": "system",
                "content": "You are Sentinel, a DevOps AI. Analyze service health and provide concise status: HEALTHY, DEGRADED, or CRITICAL with brief reasoning."
              },
              {
                "role": "user",
                "content": "Service Health Check Results:\n- Auth: {{ outputs['get-auth'].code | default('DOWN') }}\n- Payment: {{ outputs['get-payment'].code | default('DOWN') }}\n- Notification: {{ outputs['get-notify'].code | default('DOWN') }}\n\nAnalyze the overall system health."
              }
            ],
            "temperature": 0.3,
            "max_tokens": 150
          }

      # 2b. Log AI result
      - id: log-decision
        type: io.kestra.plugin.core.log.Log
        message: |
          🤖 SENTINEL AI REPORT:
          {{ outputs['ai-analysis'].body | jq(".choices[0].message.content") | first }}

      # 2c. Push to dashboard
      - id: push-to-dashboard
        type: io.kestra.plugin.core.http.Request
        uri: http://host.docker.internal:4000/api/kestra-webhook
        method: POST
        contentType: application/json
        allowFailure: true
        body: |
          {% set auth = outputs['get-auth'] | default({}) %}
          {% set payment = outputs['get-payment'] | default({}) %}
          {% set notify = outputs['get-notify'] | default({}) %}

          {
            "aiReport": {{ outputs['ai-analysis'].body | jq(".choices[0].message.content") | first | json }},
            "metrics": {
              "auth": { "code": {{ auth.code | default(500) }} },
              "payment": { "code": {{ payment.code | default(500) }} },
              "notification": { "code": {{ notify.code | default(500) }} }
            }
          }

      # 2d. Auto-healing (only when down)
      - id: heal-auth
        type: io.kestra.plugin.core.flow.If
        condition: "{{ (outputs['get-auth'].code | default(500)) != 200 }}"
        then:
          - id: log-auth-healing
            type: io.kestra.plugin.core.log.Log
            message: "🚑 AUTH SERVICE DOWN - HEALING NOW..."
          - id: restart-auth
            type: io.kestra.plugin.core.http.Request
            uri: http://auth-service:3001/simulate/healthy
            method: POST
          - id: log-auth-healed
            type: io.kestra.plugin.core.log.Log
            message: "✅ AUTH SERVICE HEALED!"

      - id: heal-payment
        type: io.kestra.plugin.core.flow.If
        condition: "{{ (outputs['get-payment'].code | default(500)) != 200 }}"
        then:
          - id: log-payment-healing
            type: io.kestra.plugin.core.log.Log
            message: "🚑 PAYMENT SERVICE DOWN - HEALING NOW..."
          - id: restart-payment
            type: io.kestra.plugin.core.http.Request
            uri: http://payment-service:3002/simulate/healthy
            method: POST
          - id: log-payment-healed
            type: io.kestra.plugin.core.log.Log
            message: "✅ PAYMENT SERVICE HEALED!"

      - id: heal-notify
        type: io.kestra.plugin.core.flow.If
        condition: "{{ (outputs['get-notify'].code | default(500)) != 200 }}"
        then:
          - id: log-notify-healing
            type: io.kestra.plugin.core.log.Log
            message: "🚑 NOTIFICATION SERVICE DOWN - HEALING NOW..."
          - id: restart-notify
            type: io.kestra.plugin.core.http.Request
            uri: http://notification-service:3003/simulate/healthy
            method: POST
          - id: log-notify-healed
            type: io.kestra.plugin.core.log.Log
            message: "✅ NOTIFICATION SERVICE HEALED!"

    else:
      # System is HEALTHY - send recovery notification
      - id: log-healthy
        type: io.kestra.plugin.core.log.Log
        message: "✅ All services healthy - System Normal"
      
      - id: push-healthy-to-dashboard
        type: io.kestra.plugin.core.http.Request
        uri: http://host.docker.internal:4000/api/kestra-webhook
        method: POST
        contentType: application/json
        allowFailure: true
        body: |
          {
            "aiReport": "HEALTHY: All services (Auth, Payment, Notification) are returning a 200 status code, indicating successful responses and normal operation.",
            "metrics": {
              "auth": { "code": {{ outputs['get-auth'].code | default(200) }} },
              "payment": { "code": {{ outputs['get-payment'].code | default(200) }} },
              "notification": { "code": {{ outputs['get-notify'].code | default(200) }} }
            }
          }


triggers:
  - id: monitor-schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * * *"
    withSeconds: true
    timezone: "Asia/Kolkata"
    lateMaximumDelay: 600000